# Generated by Django 4.0.5 on 2022-07-24 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logform', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entermodel',
        ),
    ]
