# Generated by Django 4.0.5 on 2022-06-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_category_categorie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
    ]
