# Generated by Django 4.0.5 on 2022-06-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_categorie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, choices=[('travel', 'سفر'), ('events', 'رویدادها'), ('creative', 'خلاقیت'), ('design', 'طراحی'), ('business', 'تجارت'), ('music', 'موسیقی'), ('audio', 'شنیدنی'), ('artworks', 'هنر'), ('visual', 'دیداری')], max_length=50),
        ),
    ]
