# Generated by Django 4.0.5 on 2022-06-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_image_alter_post_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
