# Generated by Django 4.0.5 on 2022-06-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(default=True, upload_to='images/comments'),
        ),
    ]
