# Generated by Django 4.0.5 on 2022-07-03 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
    ]
