# Generated by Django 4.0.5 on 2022-07-03 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_alter_comment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
    ]
