# Generated by Django 4.0.5 on 2022-07-13 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_remove_comment_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date']},
        ),
    ]
